package com.example.witnessarcana.models

import android.graphics.drawable.Drawable

data class TarotDeck(val deck: MutableList<TarotCard> = mutableListOf(
    TarotCard("The Fool","maj0","Majors",0),
    TarotCard("The Magician","maj1","Majors",1),
    TarotCard("The High Priestess","maj2","Majors",2),
    TarotCard("The Empress","maj3","Majors",3),
    TarotCard("The Emperor","maj4","Majors",4),
    TarotCard("The Hierophant","maj5","Majors",5),
    TarotCard("The Lovers","maj6","Majors",6),
    TarotCard("The Chariot","maj7","Majors",7),
    TarotCard("Strength","maj8","Majors",8),
    TarotCard("The Hermit","maj9","Majors",9),
    TarotCard("The Wheel of Fortune","maj10","Majors",10),
    TarotCard("Justice","maj11","Majors",11),
    TarotCard("The Hanged Man","maj12","Majors",12),
    TarotCard("Death","maj13","Majors",13),
    TarotCard("Temperance","maj14","Majors",14),
    TarotCard("The Devil","maj15","Majors",15),
    TarotCard("The Tower","maj16","Majors",16),
    TarotCard("The Star","maj17","Majors",17),
    TarotCard("The Moon","maj18","Majors",18),
    TarotCard("The Sun","maj19","Majors",19),
    TarotCard("Judgement","maj20","Majors",20),
    TarotCard("The World","maj21","Majors",21),

    TarotCard("Ace of Wands","min_wands1","Wands",1),
    TarotCard("Two of Wands","min_wands2","Wands",2),
    TarotCard("Three of Wands","min_wands3","Wands",3),
    TarotCard("Four of Wands","min_wands4","Wands",4),
    TarotCard("Five of Wands","min_wands5","Wands",5),
    TarotCard("Six of Wands","min_wands6","Wands",6),
    TarotCard("Seven of Wands","min_wands7","Wands",7),
    TarotCard("Eight of Wands","min_wands8","Wands",8),
    TarotCard("Nine of Wands","min_wands9","Wands",9),
    TarotCard("Ten of Wands","min_wands10","Wands",10),
    TarotCard("Page of Wands","min_wands11","Wands",11),
    TarotCard("Knight of Wands","min_wands12","Wands",12),
    TarotCard("Queen of Wands","min_wands13","Wands",13),
    TarotCard("King of Wands","min_wands14","Wands",14),

    TarotCard("Ace of Cups","min_cups1","Cups",1),
    TarotCard("Two of Cups","min_cups2","Cups",2),
    TarotCard("Three of Cups","min_cups3","Cups",3),
    TarotCard("Four of Cups","min_cups4","Cups",4),
    TarotCard("Five of Cups","min_cups5","Cups",5),
    TarotCard("Six of Cups","min_cups6","Cups",6),
    TarotCard("Seven of Cups","min_cups7","Cups",7),
    TarotCard("Eight of Cups","min_cups8","Cups",8),
    TarotCard("Nine of Cups","min_cups9","Cups",9),
    TarotCard("Ten of Cups","min_cups10","Cups",10),
    TarotCard("Page of Cups","min_cups11","Cups",11),
    TarotCard("Knight of Cups","min_cups12","Cups",12),
    TarotCard("Queen of Cups","min_cups13","Cups",13),
    TarotCard("King of Cups","min_cups14","Cups",14),

    TarotCard("Ace of Pentacles","min_pents1","Pentacles",1),
    TarotCard("Two of Pentacles","min_pents2","Pentacles",2),
    TarotCard("Three of Pentacles","min_pents3","Pentacles",3),
    TarotCard("Four of Pentacles","min_pents4","Pentacles",4),
    TarotCard("Five of Pentacles","min_pents5","Pentacles",5),
    TarotCard("Six of Pentacles","min_pents6","Pentacles",6),
    TarotCard("Seven of Pentacles","min_pents7","Pentacles",7),
    TarotCard("Eight of Pentacles","min_pents8","Pentacles",8),
    TarotCard("Nine of Pentacles","min_pents9","Pentacles",9),
    TarotCard("Ten of Pentacles","min_pents10","Pentacles",10),
    TarotCard("Page of Pentacles","min_pents11","Pentacles",11),
    TarotCard("Knight of Pentacles","min_pents12","Pentacles",12),
    TarotCard("Queen of Pentacles","min_pents13","Pentacles",13),
    TarotCard("King of Pentacles","min_pents14","Pentacles",14),

    TarotCard("Ace of Swords","min_swords1","Swords",1),
    TarotCard("Two of Swords","min_swords2","Swords",2),
    TarotCard("Three of Swords","min_swords3","Swords",3),
    TarotCard("Four of Swords","min_swords4","Swords",4),
    TarotCard("Five of Swords","min_swords5","Swords",5),
    TarotCard("Six of Swords","min_swords6","Swords",6),
    TarotCard("Seven of Swords","min_swords7","Swords",7),
    TarotCard("Eight of Swords","min_swords8","Swords",8),
    TarotCard("Nine of Swords","min_swords9","Swords",9),
    TarotCard("Ten of Swords","min_swords10","Swords",10),
    TarotCard("Page of Swords","min_swords11","Swords",11),
    TarotCard("Knight of Swords","min_swords12","Swords",12),
    TarotCard("Queen of Swords","min_swords13","Swords",13),
    TarotCard("King of Swords","min_swords14","Swords",14),

    )
)

data class TarotCard(
    val title: String,
    val id: String,
    val suite: String,
    val number: Int
)


